spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testsqldb?characterEncoding=utf-8&useSSL=false
    username: root
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
server:
  port: 8080


